apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasktest
  template:
    metadata:
      labels:
        app: flasktest
    spec:
      containers:
      - name: flask-app
        image: flasktest:latest 
        ports:
        - containerPort: 5000 